### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [vazquezstudio/prj-rev-bwfs-dasmoto#5]
https://github.com/vazquezstudio/prj-rev-bwfs-dasmoto/blob/master/DasmotosAC/resources/css/style.css#L12-L16

This is a lot of repetition. Move shared styles into their own CSS rule.

```css
h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

Notice I didn't include the font here because that would also be repeated. Since all text on the page has Helvetica font, just use the universal selector and remove it from everywhere that its repeated.

```css
* {
  font-family: Helvetica;
}
```
